version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frankenphp
    hostname: frankenphp
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - .:/app
      - ./Caddyfile:/etc/frankenphp/Caddyfile
